name: Build and Package

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  VERSION: '1.2.3'

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest
    environment: Auto Build And Release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos > theos
         sed -i '' 's/get_sdks$//g' theos
         bash theos
         brew install make

      - name: Set env
        run: |
          echo "THEOS=~/theos" >> $GITHUB_ENV
          sT=$(TZ=UTC-8 date +'%S')
          echo "msT=$(date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
          echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo ${{ env.VERSION }}
          echo ${{ env.msT }}
          echo ${{ env.logT }}

      - name: Pre body
        run: |
          echo -e "更新时间：${{ env.logT }}" >> release.txt
          echo -e "> - 同步官方1.2.1正式版更新，修复异常发热问题。M哥的编译版本特别说明：1.首页只增加了重启按钮。2.设置里面改为点击空白关闭。3.点击更新可以直接在巨魔安装。其他全部是原生官方代码！！" >> release.txt
          sed -i '' "s/AAA/${{ env.msT }}/g" ./Bootstrap/Views/ContentView.swift
      
      - name: Build Bootstrap
        run: |
          gmake -j$(sysctl -n hw.ncpu) package
          mv ./packages/Bootstrap.tipa Bootstrap.ipa

      - name: Release ipa
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.msT }}
          target_commitish: main
          body_path: release.txt
          latest: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.ipa
